### ISSUE TITLE
Go build fails due to Golang cross compile undefined errors with C module

### ISSUE THREAD

**Issue by dp-dev** [cloudfoundry/go-cfclient#426]
Hi all,

we are making use of this go-cfclient inside our project at SAP/BTP (Business Technology Platform). During the last update from version `v3.0.0-alpha.7` -> `v3.0.0-alpha.8` we saw that our build process started to fail. We are executing the build with the following parameters which worked fine in version `v3.0.0-alpha.7` but now produces the following error:

```
GOOS=linux GOARCH=amd64 go build -o app/linux-amd64/ourapp -mod vendor
# github.com/cloudfoundry/go-cfclient/v3/resource
vendor/github.com/cloudfoundry/go-cfclient/v3/resource/build.go:24:16: undefined: Lifecycle
vendor/github.com/cloudfoundry/go-cfclient/v3/resource/build.go:35:37: undefined: Lifecycle
vendor/github.com/cloudfoundry/go-cfclient/v3/resource/droplet.go:22:20: undefined: Lifecycle
vendor/github.com/cloudfoundry/go-cfclient/v3/resource/service_credential_binding.go:55:22: undefined: App
```

This build command is running on a central build infrastructure for the whole company, so we can't influence these parameters. I checked the build command and found out that the specification of the operating system is the problem. Without specifying it the go build works accordingly -> `GOARCH=amd64 go build -o app/linux-amd64/ourapp -mod vendor` ✅ 

I did some further digging into this issue and found the following stackoverflow thread where the problem was raised as well: https://stackoverflow.com/questions/62204478/golang-cross-compile-undefined-errors
```
GOOS=linux GOARCH=amd64 go build -v gitlab.com/project/project-data-convertor
gitlab.com/project/project-data-convertor
# gitlab.com/project/project-data-convertor
./utils.go:253:50: undefined: beamLocation
./utils.go:278:36: undefined: beamLocation
./utils.go:278:50: undefined: beamLocations
./utils.go:278:50: too many errors
```
> Answer: I know it's a bit too late to answer this question but this problem came, on my side, from the import of C module. For those who have this problem of cross-platform compilation, check that you don't import C module : normally it should work.

I had a look and found that this is also causing our problem, as one of the changes from `v3.0.0-alpha.7` -> `v3.0.0-alpha.8` introduces the `C` module here: https://github.com/cloudfoundry/go-cfclient/blob/66cca9d17218b886c072d76aa74ff4680efc86ad/resource/app.go#L4 once this is removed the build works again as expected.

Therefore, I would like to propose to remove this library again introduced by @robertjsullivan with PR #425. Would that be possible to unblock us?

**Comment by sneal** [comment]
Fixed by #427
